/*
 * Copyright 2017 Peng Wan <phylame@163.com>
 *
 * This file is part of Jem.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import jclp.log.Log
import jclp.log.LogLevel
import jclp.setting.MapSettings
import jem.Book
import jem.Build
import jem.epm.from
import jem.epm.write
import java.util.zip.Deflater

fun main(args: Array<String>) {
    Log.level = LogLevel.ALL
    val settings = MapSettings()
    settings["maker.file.overwrite"] = true
    settings["maker.vdm.type"] = "dir"
    settings["maker.vdm.zipLevel"] = Deflater.DEFAULT_COMPRESSION
    settings["maker.vdm.comment"] = "Generated by jem v${Build.VERSION}"
    settings["maker.pmab.encoding"] = "GB18030"
    settings["maker.xml.indent"] = "  "
    settings["maker.pmab.meta"] = mapOf("version" to "5.0", "vendor" to null)
    Book.from("E:/tmp/3.pmab")?.apply {
        write("E:/tmp/4.pmab/.", arguments = settings)
    }
}
