/*
 * Copyright 2016 Peng Wan <phylame@163.com>
 *
 * This file is part of Jem.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package pw.phylame.jem.epm.base;

import pw.phylame.jem.epm.util.config.AbstractConfig;
import pw.phylame.jem.epm.util.config.Mapped;
import pw.phylame.jem.util.Build;

import java.util.zip.Deflater;

public class ZipOutConfig extends AbstractConfig {
    public static final String ZIP_METHOD = "zip.method";
    public static final String ZIP_LEVEL = "zip.level";
    public static final String ZIP_COMMENT = "zip.comment";

    /**
     * Compression method of ZIP entry.
     */
    @Mapped(ZIP_METHOD)
    public int zipMethod = Deflater.DEFLATED;

    /**
     * Compression level of ZIP entry.
     */
    @Mapped(ZIP_LEVEL)
    public int zipLevel = Deflater.DEFAULT_COMPRESSION;

    /**
     * Comment string for ZIP.
     */
    @Mapped(ZIP_COMMENT)
    public String zipComment = String.format("generated by %s v%s", Build.NAME, Build.VERSION);
}
